### PR TITLE
hlspxd: fix comments, typos, MSVC build

### PR DESCRIPTION
**Pull request by lebdron**
Compile tested: x64-3.2
Run tested: Ubuntu 18.04 container x64. Tested general functionality with a sample playlist.

- Fix typos and translate comments
- Remove redundant `const &` for `const char *`, which fixes MSVC build
- Add `std::terminate` and print to `cerr` if logfile cannot be opened

### CODE REVIEW

**Comment by ryzhovau** [comment]
Thanks! I'll merge this PR as a [patch](https://github.com/Entware/rtndev/pull/5.patch) to original code if you don't mind. 
We keep local copy at `src` folder because original src URL is [broken](http://hlspx.ocry.com/) for now.

**Comment by lebdron** [comment]
Sure, thank you!

**Comment by ryzhovau** [comment]
Merged as https://github.com/Entware/rtndev/commit/a042cfae2c421f5c9e789ade0ede3a819fe0335a

**Comment by jschwartzenberg** [comment]
Does anybody know who created the original program? I made some changes to hlspxd to make it work with my TV.

I could create a PR with my patch, but I'm compiling the sources on a regular Ubuntu/Raspbian installation, so I haven't been using the build infrastructure that would pick up such a patch.

**Comment by ryzhovau** [comment]
It's hard to find.

This sources was taken from [homepage](http://hlspx.ocry.com) which is offline now. 
No forks, no sources, no any tracks of author in code.

> I could create a PR with my patch, but I'm compiling the sources on a regular Ubuntu/Raspbian installation, so I haven't been using the build infrastructure that would pick up such a patch.

You may leave this patch here, on pastebin.com, gist.github.com or on any other site you prefer. At least for history.

**Comment by jschwartzenberg** [comment]
I've created a patch that contains the output of `git format-patch --stdout` here: https://github.com/Entware/rtndev/pull/7

In my own fork, I also have a separate branch that has all the patches applied to it already. Please let me know if there are any problems. I'll update the PR in that case.

**Pull request closed without merging**
